function [features,featureNames] = getInterplayTILFeatures(nucleiCentroids, nucleiArea, MedianIntensity, isLymphocyte, image)

% extracts the nuclei that are near to each centroid by using a threshold
[filtcentroids, filtareas, filtintensities, filtpreds, Kparameter] = filtCentroidsByTresh(nucleiCentroids, MedianIntensity, nucleiArea, isLymphocyte);
%  Structure of filts variables:
% K x T cell, where T = quantity of nuclei; K = thresholds of 5dL, 10dL, 15dL;
% dL = mean of a diameter of a Lymp.(8px at 40X);
% inside a cell = array of the filteres nuclei by each specific radious 

%  [Nuclei x K1 K2 K3]

% Function No. 1
sumInvDistLymp = extractSumInvDistLymp(nucleiCentroids, Kparameter);

% Function No. 2 y 4
[RatioAreaLympNonLymp,  totalAreaLymp, ratioNumLympNonLymp] = extractRatioAreaLympNonLymp(filtcentroids, filtareas, filtpreds, Kparameter);

% Function No. 3
ratioAreaLympSample = extractRatioAreaLympSample(nucleiCentroids, totalAreaLymp, Kparameter, image);

% Function No. 5, 11
[intensityDifferenceMedian, sumDistLymptoNonLymp] = getIntensityDifferenceMedian(length(nucleiCentroids), nucleiCentroids, filtcentroids, MedianIntensity, filtintensities,filtpreds, Kparameter);

% Function No. 6, 7 , 10
[convexHullAreaRatio, convexHullIntersectedArea, numLymInNonLympArea] = getConvexHullAreaRatio(length(nucleiCentroids), filtcentroids, filtpreds, Kparameter);

% Function No. 8 y 9
[mediamDistLympNonLympNeig, ratioMediamDistLympNonLympNeig] = extractMediamDistLympToNonLympNeig(nucleiCentroids, filtcentroids, filtpreds, Kparameter);

% Function No. 12
areaSample= extractAreaSample(nucleiCentroids, Kparameter, image);

% all the features extracted
features = [sumInvDistLymp RatioAreaLympNonLymp ratioAreaLympSample ratioNumLympNonLymp intensityDifferenceMedian convexHullAreaRatio convexHullIntersectedArea mediamDistLympNonLympNeig ratioMediamDistLympNonLympNeig numLymInNonLympArea sumDistLymptoNonLymp areaSample];

featureNames = {'sumInvDistLympK1','sumInvDistLympK2','sumInvDistLympK3','RatioAreaLympNonLympK1',...
'RatioAreaLympNonLympK2','RatioAreaLympNonLympK3','ratioAreaLympSampleK1','ratioAreaLympSampleK2',...
'ratioAreaLympSampleK3','ratioNumLympNonLympK1','ratioNumLympNonLympK2',...
'ratioNumLympNonLympK3','intensityDifferenceMedianK1','intensityDifferenceMedianK2',...
'intensityDifferenceMedianK3','convexHullAreaRatioK1','convexHullAreaRatioK2',...
'convexHullAreaRatioK3','convexHullIntersectedAreaK1','convexHullIntersectedAreaK2',...
'convexHullIntersectedAreaK3','mediamDistLympNonLympNeigK1','mediamDistLympNonLympNeigK2',...
'mediamDistLympNonLympNeigK3','ratioMediamDistLympNonLympNeigK1',...
'ratioMediamDistLympNonLympNeigK2','ratioMediamDistLympNonLympNeigK3',...
'numLymInNonLympAreaK1','numLymInNonLympAreaK2','numLymInNonLympAreaK3',...
'sumDistLymptoNonLympK1','sumDistLymptoNonLympK2','sumDistLymptoNonLympK3',...
'sampleAreaK1','sampleentropyIntensityK1','sampleMaxIntensityK1',...
'samplemedIntensityK1','sampleMinIntensityK1','sampleedgeMedIntensityK1',...
'sampleentropyRedK1','sampleratioMedRBK1','sampleratioMedRGK1',...
'sampleharFeat_energyAngularSecondMomentK1','sampleharFeat_ContrastK1',...
'sampleharFeat_correlationK1','sampleharFeat_VarianceK1','sampleharFeat_InverseDifferenceMomentK1',...
'sampleharFeat_SumAverageK1','sampleharFeat_SumVarianceK1','sampleharFeat_SumEntropyK1',...
'sampleharFeat_EntropyK1','sampleharFeat_DifferenceVarianceK1','sampleharFeat_DifferenceEntropyK1',...
'sampleharFeat_InformationMeasuresCorrelationIK1','sampleharFeat_InformationMeasuresCorrelationIIK1',...
'sampleharFeat_MaximalCorrelationCoefficientK1','sampleAreaK2','sampleentropyIntensityK2',...
'sampleMaxIntensityK2','samplemedIntensityK2','sampleMinIntensityK2','sampleedgeMedIntensityK2',...
'sampleentropyRedK2','sampleratioMedRBK2','sampleratioMedRGK2',...
'sampleharFeat_energyAngularSecondMomentK2','sampleharFeat_ContrastK2',...
'sampleharFeat_correlationK2','sampleharFeat_VarianceK2','sampleharFeat_InverseDifferenceMomentK2',...
'sampleharFeat_SumAverageK2','sampleharFeat_SumVarianceK2','sampleharFeat_SumEntropyK2',...
'sampleharFeat_EntropyK2','sampleharFeat_DifferenceVarianceK2',...
'sampleharFeat_DifferenceEntropyK2','sampleharFeat_InformationMeasuresCorrelationIK2',...
'sampleharFeat_InformationMeasuresCorrelationIIK2',...
'sampleharFeat_MaximalCorrelationCoefficientK2','sampleAreaK3','sampleentropyIntensityK3',...
'sampleMaxIntensityK3','samplemedIntensityK3','sampleMinIntensityK3','sampleedgeMedIntensityK3',...
'sampleentropyRedK3','sampleratioMedRBK3','sampleratioMedRGK3',...
'sampleharFeat_energyAngularSecondMomentK3','sampleharFeat_ContrastK3',...
'sampleharFeat_correlationK3','sampleharFeat_VarianceK3',...
'sampleharFeat_InverseDifferenceMomentK3','sampleharFeat_SumAverageK3',...
'sampleharFeat_SumVarianceK3','sampleharFeat_SumEntropyK3','sampleharFeat_EntropyK3',...
'sampleharFeat_DifferenceVarianceK3','sampleharFeat_DifferenceEntropyK3',...
'sampleharFeat_InformationMeasuresCorrelationIK3',...
'sampleharFeat_InformationMeasuresCorrelationIIK3','sampleharFeat_MaximalCorrelationCoefficientK3'};

end